global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'hytale'
    static_configs:
      - targets: ['dashboard:8088']
    metrics_path: /metrics
    scrape_interval: 5s
